module.exports = {
  apps: [
    {
      name: 'cbrsx-backend-8080',
      cwd: './backend',
      script: 'java',
      args: '-jar target/cbrsx-backend-1.0.0-SNAPSHOT.jar',
      env: {
        SPRING_PROFILES_ACTIVE: 'prod',
        SERVER_PORT: 8080,
      },
      max_memory_restart: '1G',
      kill_timeout: 10000,
      max_restarts: 5,
      min_uptime: '20s',
      restart_delay: 3000,
      out_file: './logs/backend-out.log',
      error_file: './logs/backend-error.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'cbrsx-admin-3000',
      cwd: './dashboard',
      script: 'npx',
      args: 'vite preview --host --port 3000 --strictPort',
      env: {
        NODE_ENV: 'production',
      },
      max_memory_restart: '400M',
      kill_timeout: 5000,
      max_restarts: 5,
      min_uptime: '15s',
      out_file: '../logs/admin-out.log',
      error_file: '../logs/admin-error.log',
      time: true,
    },
    {
      name: 'cbrsx-trainee-5000',
      cwd: './trainee_view',
      script: 'npx',
      args: 'vite preview --host --port 5000 --strictPort',
      env: {
        NODE_ENV: 'production',
      },
      max_memory_restart: '400M',
      kill_timeout: 5000,
      max_restarts: 5,
      min_uptime: '15s',
      out_file: '../logs/trainee-out.log',
      error_file: '../logs/trainee-error.log',
      time: true,
    },
  ],
};
